using Azure.Core;
using ECommerceBackend.Application.DTOs;
using ECommerceBackend.Application.Interfaces;
using ECommerceBackend.Application.Models;
using ECommerceBackend.Domain.Entities;
using ECommerceBackend.Infrastructure.Repositories;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.Data;
using Microsoft.IdentityModel.Tokens;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Security.Cryptography;
using System.Text;

namespace ECommerceBackend.Application.Services
{
    public class AuthService : IAuthService
    {
        private readonly IUserRepository _userRepository;

        public AuthService(IUserRepository userRepository)
        {
            _userRepository = userRepository;
        }
        private string GenerateAccessToken(User user)
        {
            var claims = new[]
            {
                new Claim(ClaimTypes.Name, user.Email),
                new Claim(ClaimTypes.NameIdentifier, user.UserId.ToString())
            };

            var key = new SymmetricSecurityKey(Encoding.UTF8.GetBytes("this_is_a_very_long_secret_key@2025!!"));
            var creds = new SigningCredentials(key, SecurityAlgorithms.HmacSha256);

            var token = new JwtSecurityToken(
                issuer: "yourdomain.com",
                audience: "yourdomain.com",
                claims: claims,
                expires: DateTime.UtcNow.AddMinutes(15), // Short life access token
                signingCredentials: creds);

            return new JwtSecurityTokenHandler().WriteToken(token);
        }

        private string GenerateRefreshToken()
        {
            var randomBytes = new byte[64];
            using var rng = RandomNumberGenerator.Create();
            rng.GetBytes(randomBytes);
            return Convert.ToBase64String(randomBytes);
        }

        private static bool VerifyPassword(User user, string Password)
        {
            var passwordHasher = new PasswordHasher<User>();
            var result = passwordHasher.VerifyHashedPassword(user, user.PasswordHash, Password);

            if (result == PasswordVerificationResult.Failed)
                return false;

            return true;
        }


        public async Task<AuthResponse> AuthenticateAsync(LoginModel model)
        {
            //var user = new User
            //{
            //    Id = 1, // Set to 0 if it's auto-generated by the database
            //    Name = "Animesh", // Replace with the actual name
            //    Email = model.Email, // Use the email from the LoginModel
            //    PasswordHash = "123456" // Hash the password
            //};

            var existingUser = await _userRepository.GetUserByEmailAsync(model.Email);
            if (existingUser == null || !VerifyPassword(existingUser, model.Password))
                throw new UnauthorizedAccessException("Invalid credentials");

            var accessToken = GenerateAccessToken(existingUser);
            var refreshToken = GenerateRefreshToken();

            return await Task.FromResult(new AuthResponse
            {
                AccessToken = accessToken,
                RefreshToken = refreshToken,
                UserId = existingUser.UserId
            });
        }
        public async Task<AuthResponse> RegisterAsync(RegisterModel model)
        {
            var existingUser = await _userRepository.GetUserByEmailAsync(model.Email);
            if (existingUser != null)
                throw new Exception("User already exists");

            // Ensure all required properties of the User object are set
            var user = new User
            {
                UserId = Guid.NewGuid(), // Generate a new GUID for the UserId
                Name = model.Name,
                Email = model.Email,
                PasswordHash = string.Empty // Initialize PasswordHash to satisfy the required property
            };

            // Now hash the password using the user object
            var passwordHasher = new PasswordHasher<User>();
            user.PasswordHash = passwordHasher.HashPassword(user, model.Password);

            await _userRepository.AddAsync(user);

            var accessToken = GenerateAccessToken(user);
            var refreshToken = GenerateRefreshToken();

            return new AuthResponse
            {
                AccessToken = accessToken,
                RefreshToken = refreshToken,
                UserId = user.UserId
            };
        }


    }
}
