// <auto-generated />
using System;
using ECommerceBackend.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerceBackend.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260721181229_AddProductCategoryIndex")]
    partial class AddProductCategoryIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECommerceBackend.Domain.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("ECommerceBackend.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReservationExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StockSettledAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Zip")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ECommerceBackend.Domain.Entities.OrderLineItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("ECommerceBackend.Domain.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt");

                    b.ToTable("OutboxMessages");
                });

            modelBuilder.Entity("ECommerceBackend.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Image")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RatingCount")
                        .HasColumnType("int");

                    b.Property<double>("RatingRate")
                        .HasColumnType("float");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "men's clothing",
                            Description = "Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday",
                            Image = "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_t.png",
                            Price = 109.95m,
                            RatingCount = 120,
                            RatingRate = 3.8999999999999999,
                            StockQuantity = 100,
                            Title = "Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops"
                        },
                        new
                        {
                            Id = 2,
                            Category = "men's clothing",
                            Description = "Slim-fitting style, contrast raglan long sleeve, three-button henley placket, light weight & soft fabric for breathable and comfortable wearing.",
                            Image = "https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_t.png",
                            Price = 22.30m,
                            RatingCount = 259,
                            RatingRate = 4.0999999999999996,
                            StockQuantity = 100,
                            Title = "Mens Casual Premium Slim Fit T-Shirts"
                        },
                        new
                        {
                            Id = 3,
                            Category = "men's clothing",
                            Description = "great outerwear jackets for Spring/Autumn/Winter, suitable for many occasions, such as working, hiking, camping, mountain/rock climbing, cycling, traveling or other outdoors.",
                            Image = "https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_t.png",
                            Price = 55.99m,
                            RatingCount = 500,
                            RatingRate = 4.7000000000000002,
                            StockQuantity = 100,
                            Title = "Mens Cotton Jacket"
                        },
                        new
                        {
                            Id = 4,
                            Category = "men's clothing",
                            Description = "The color could be slightly different between on the screen and in practice. Please note that body builds vary by person, therefore, detailed size information should be reviewed below on the product description.",
                            Image = "https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_t.png",
                            Price = 15.99m,
                            RatingCount = 430,
                            RatingRate = 2.1000000000000001,
                            StockQuantity = 100,
                            Title = "Mens Casual Slim Fit"
                        },
                        new
                        {
                            Id = 5,
                            Category = "jewelery",
                            Description = "From our Legends Collection, the Naga was inspired by the mythical water dragon that protects the ocean's pearl. Wear facing inward to be bestowed with love and abundance, or outward for protection.",
                            Image = "https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_t.png",
                            Price = 695m,
                            RatingCount = 400,
                            RatingRate = 4.5999999999999996,
                            StockQuantity = 100,
                            Title = "John Hardy Women's Legends Naga Gold & Silver Dragon Station Chain Bracelet"
                        },
                        new
                        {
                            Id = 6,
                            Category = "jewelery",
                            Description = "Satisfaction Guaranteed. Return or exchange any order within 30 days. Designed and sold by Hafeez Center in the United States.",
                            Image = "https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_t.png",
                            Price = 168m,
                            RatingCount = 70,
                            RatingRate = 3.8999999999999999,
                            StockQuantity = 100,
                            Title = "Solid Gold Petite Micropave"
                        },
                        new
                        {
                            Id = 7,
                            Category = "jewelery",
                            Description = "Classic Created Wedding Engagement Solitaire Diamond Promise Ring for Her. Gifts to spoil your love more for Engagement, Wedding, Anniversary, Valentine's Day.",
                            Image = "https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_t.png",
                            Price = 9.99m,
                            RatingCount = 400,
                            RatingRate = 3.0,
                            StockQuantity = 100,
                            Title = "White Gold Plated Princess"
                        },
                        new
                        {
                            Id = 8,
                            Category = "jewelery",
                            Description = "Rose Gold Plated Double Flared Tunnel Plug Earrings. Made of 316L Stainless Steel",
                            Image = "https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_t.png",
                            Price = 10.99m,
                            RatingCount = 100,
                            RatingRate = 1.8999999999999999,
                            StockQuantity = 100,
                            Title = "Pierced Owl Rose Gold Plated Stainless Steel Double"
                        },
                        new
                        {
                            Id = 9,
                            Category = "electronics",
                            Description = "USB 3.0 and USB 2.0 Compatibility Fast data transfers Improve PC Performance High Capacity; Compatibility Formatted NTFS for Windows 10, Windows 8.1, Windows 7.",
                            Image = "https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_t.png",
                            Price = 64m,
                            RatingCount = 203,
                            RatingRate = 3.2999999999999998,
                            StockQuantity = 100,
                            Title = "WD 2TB Elements Portable External Hard Drive - USB 3.0"
                        },
                        new
                        {
                            Id = 10,
                            Category = "electronics",
                            Description = "Easy upgrade for faster boot up, shutdown, application load and response. Boosts burst write performance, making it ideal for typical PC workloads.",
                            Image = "https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_t.png",
                            Price = 109m,
                            RatingCount = 470,
                            RatingRate = 2.8999999999999999,
                            StockQuantity = 100,
                            Title = "SanDisk SSD PLUS 1TB Internal SSD - SATA III 6 Gb/s"
                        },
                        new
                        {
                            Id = 11,
                            Category = "electronics",
                            Description = "3D NAND flash are applied to deliver high transfer speeds Remarkable transfer speeds that enable faster bootup and improved overall system performance.",
                            Image = "https://fakestoreapi.com/img/71kWymZ+c+L._AC_SX679_t.png",
                            Price = 109m,
                            RatingCount = 319,
                            RatingRate = 4.7999999999999998,
                            StockQuantity = 100,
                            Title = "Silicon Power 256GB SSD 3D NAND A55 SLC Cache Performance Boost SATA III 2.5"
                        },
                        new
                        {
                            Id = 12,
                            Category = "electronics",
                            Description = "Expand your PS4 gaming experience, Play anywhere Fast and easy, setup Sleek design with high capacity, 3-year manufacturer's limited warranty.",
                            Image = "https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_t.png",
                            Price = 114m,
                            RatingCount = 400,
                            RatingRate = 4.7999999999999998,
                            StockQuantity = 100,
                            Title = "WD 4TB Gaming Drive Works with Playstation 4 Portable External Hard Drive"
                        },
                        new
                        {
                            Id = 13,
                            Category = "electronics",
                            Description = "21.5 inches Full HD (1920 x 1080) widescreen IPS display And Radeon free Sync technology. No compatibility for VESA Mount Refresh Rate: 75Hz.",
                            Image = "https://fakestoreapi.com/img/81QpkIctqPL._AC_SX679_t.png",
                            Price = 599m,
                            RatingCount = 250,
                            RatingRate = 2.8999999999999999,
                            StockQuantity = 100,
                            Title = "Acer SB220Q bi 21.5 inches Full HD (1920 x 1080) IPS Ultra-Thin"
                        },
                        new
                        {
                            Id = 14,
                            Category = "electronics",
                            Description = "49 INCH SUPER ULTRAWIDE 32:9 CURVED GAMING MONITOR with dual 27 inch screen side by side QUANTUM DOT (QLED) TECHNOLOGY, HDR support and factory calibration.",
                            Image = "https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_t.png",
                            Price = 999.99m,
                            RatingCount = 140,
                            RatingRate = 2.2000000000000002,
                            StockQuantity = 100,
                            Title = "Samsung 49-Inch CHG90 144Hz Curved Gaming Monitor (LC49HG90DMNXZA) - Super Ultrawide Screen QLED"
                        },
                        new
                        {
                            Id = 15,
                            Category = "women's clothing",
                            Description = "Note: The Jackets is US standard size, Please choose size as your usual wear Material: 100% Polyester; Detachable Liner Fabric: Warm Fleece.",
                            Image = "https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_t.png",
                            Price = 56.99m,
                            RatingCount = 235,
                            RatingRate = 2.6000000000000001,
                            StockQuantity = 100,
                            Title = "BIYLACLESEN Women's 3-in-1 Snowboard Jacket Winter Coats"
                        },
                        new
                        {
                            Id = 16,
                            Category = "women's clothing",
                            Description = "100% POLYURETHANE(shell) 100% POLYESTER(lining) 75% POLYESTER 25% COTTON (SWEATER), Faux leather material for style and comfort.",
                            Image = "https://fakestoreapi.com/img/81XH0e8fefL._AC_UY879_t.png",
                            Price = 29.95m,
                            RatingCount = 340,
                            RatingRate = 2.8999999999999999,
                            StockQuantity = 100,
                            Title = "Lock and Love Women's Removable Hooded Faux Leather Moto Biker Jacket"
                        },
                        new
                        {
                            Id = 17,
                            Category = "women's clothing",
                            Description = "Lightweight perfet for trip or casual wear---Long sleeve with hooded, adjustable drawstring waist design. Button and zipper front closure raincoat.",
                            Image = "https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2t.png",
                            Price = 39.99m,
                            RatingCount = 679,
                            RatingRate = 3.7999999999999998,
                            StockQuantity = 100,
                            Title = "Rain Jacket Women Windbreaker Striped Climbing Raincoats"
                        },
                        new
                        {
                            Id = 18,
                            Category = "women's clothing",
                            Description = "95% RAYON 5% SPANDEX, Made in USA or Imported, Do Not Bleach, Lightweight fabric with great stretch for comfort.",
                            Image = "https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_t.png",
                            Price = 9.85m,
                            RatingCount = 130,
                            RatingRate = 4.7000000000000002,
                            StockQuantity = 100,
                            Title = "MBJ Women's Solid Short Sleeve Boat Neck V"
                        },
                        new
                        {
                            Id = 19,
                            Category = "women's clothing",
                            Description = "100% Polyester, Machine wash, 100% cationic polyester interlock, Machine Wash & Pre Shrunk for a Great Fit, Lightweight, roomy and highly breathable.",
                            Image = "https://fakestoreapi.com/img/51eg55uWmdL._AC_UX679_t.png",
                            Price = 7.95m,
                            RatingCount = 146,
                            RatingRate = 4.5,
                            StockQuantity = 100,
                            Title = "Opna Women's Short Sleeve Moisture"
                        },
                        new
                        {
                            Id = 20,
                            Category = "women's clothing",
                            Description = "95% Cotton, 5% Spandex, Features: Casual, Short Sleeve, Letter Print, V-Neck, Fashion Tees, The fabric is soft and has some stretch.",
                            Image = "https://fakestoreapi.com/img/61pHAEJ4NML._AC_UX679_t.png",
                            Price = 12.99m,
                            RatingCount = 145,
                            RatingRate = 3.6000000000000001,
                            StockQuantity = 100,
                            Title = "DANVOUY Womens T Shirt Casual Cotton Short"
                        });
                });

            modelBuilder.Entity("ECommerceBackend.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("ECommerceBackend.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ECommerceBackend.Domain.Entities.UserInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfItems")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserInvoice");
                });

            modelBuilder.Entity("ECommerceBackend.Domain.Entities.CartItem", b =>
                {
                    b.HasOne("ECommerceBackend.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Users_CartItems");
                });

            modelBuilder.Entity("ECommerceBackend.Domain.Entities.OrderLineItem", b =>
                {
                    b.HasOne("ECommerceBackend.Domain.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ECommerceBackend.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("ECommerceBackend.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RefreshTokens_Users_UserId");
                });

            modelBuilder.Entity("ECommerceBackend.Domain.Entities.UserInvoice", b =>
                {
                    b.HasOne("ECommerceBackend.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Users_CustomerInvoices_UserId");
                });

            modelBuilder.Entity("ECommerceBackend.Domain.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
